### ISSUE TITLE
Can I use this only on variables and whitelist all functions?

### ISSUE THREAD

**Issue by jericopulvera** [ptkdev/eslint-plugin-snakecasejs#2]
Can I use this only on variables and whitelist all functions?

**Comment by ptkdev** [comment]
Hi!
Yes, use `"snakecasejs/filter"` and set all filters you find in your project.
You can get name of Identifiers for filter array in the popup: 
![](https://media.discordapp.net/attachments/536874407256260618/687956308863090710/snakecasejs.png)

Function identifier is: `MethodDefinition`, try: 
`"snakecasejs/filter": ["ClassDeclaration", "NewExpression", "MethodDefinition"],`
